In [1]:
import numpy as np

y = np.array([10,50,100,200,70,20])
X = np.array([
    [30,7,1,1.5,2],
    [40,10,0,1.6,4],
    [50,20,1,1.7,5],
    [60,12,0,1.8,7],
    [25,10,1,1.65,7],
    [24,12,0,1.62,0]
])

X.shape

(6, 5)

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a.shape, b.shape

((3,), (3,))

In [3]:
a

array([1, 2, 3])

In [4]:
c = np.c_[a,b]
c.shape

(3, 2)

In [5]:
d = np.c_[np.ones((3,)),c]
d

array([[1., 1., 4.],
       [1., 2., 5.],
       [1., 3., 6.]])

In [6]:
e = np.c_[np.ones((c.shape[0],1)),c]
e

array([[1., 1., 4.],
       [1., 2., 5.],
       [1., 3., 6.]])

In [7]:
c = X
f = np.c_[np.ones((c.shape[0],1)),c]
f

array([[ 1.  , 30.  ,  7.  ,  1.  ,  1.5 ,  2.  ],
       [ 1.  , 40.  , 10.  ,  0.  ,  1.6 ,  4.  ],
       [ 1.  , 50.  , 20.  ,  1.  ,  1.7 ,  5.  ],
       [ 1.  , 60.  , 12.  ,  0.  ,  1.8 ,  7.  ],
       [ 1.  , 25.  , 10.  ,  1.  ,  1.65,  7.  ],
       [ 1.  , 24.  , 12.  ,  0.  ,  1.62,  0.  ]])

In [8]:
# note que podemos adicionar mais linhas e colunas na matriz X que a função abaixo continua funcionando
g = np.c_[np.ones((X.shape[0])),X]
g

array([[ 1.  , 30.  ,  7.  ,  1.  ,  1.5 ,  2.  ],
       [ 1.  , 40.  , 10.  ,  0.  ,  1.6 ,  4.  ],
       [ 1.  , 50.  , 20.  ,  1.  ,  1.7 ,  5.  ],
       [ 1.  , 60.  , 12.  ,  0.  ,  1.8 ,  7.  ],
       [ 1.  , 25.  , 10.  ,  1.  ,  1.65,  7.  ],
       [ 1.  , 24.  , 12.  ,  0.  ,  1.62,  0.  ]])

In [9]:
# Vamos implementar o beta matricial (Xt.X)^-1 Xt Y
# começando pelo (Xt.X)
beta = np.linalg.inv(np.dot(g.T,g))
beta

array([[ 3.12252391e+02,  2.95975034e-02,  2.25162392e+00,
        -1.94089862e+01, -2.13191156e+02,  4.93064765e+00],
       [ 2.95975034e-02,  2.39263519e-03, -2.95507914e-03,
         2.12626968e-02, -4.43549390e-02, -5.66770808e-03],
       [ 2.25162392e+00, -2.95507914e-03,  3.30578512e-02,
        -1.85050776e-01, -1.59098533e+00,  4.31215882e-02],
       [-1.94089862e+01,  2.12626968e-02, -1.85050776e-01,
         2.11644271e+00,  1.29910432e+01, -3.93902408e-01],
       [-2.13191156e+02, -4.43549390e-02, -1.59098533e+00,
         1.29910432e+01,  1.46661136e+02, -3.37017481e+00],
       [ 4.93064765e+00, -5.66770808e-03,  4.31215882e-02,
        -3.93902408e-01, -3.37017481e+00,  1.23908763e-01]])

In [10]:
# verificando se a matriz identidade multiplicada por essa matriz resulta em uma matriz de 1 na diagonal
# se multiplicar a matriz pela inversa dela deve resultar na matriz com 1 na diagonal e 0 no resto
test = np.dot(g.T,g)
np.round(np.dot(np.linalg.inv(test),test))

array([[ 1., -0., -0., -0., -0., -0.],
       [-0.,  1., -0., -0., -0., -0.],
       [-0., -0.,  1., -0., -0.,  0.],
       [-0., -0.,  0.,  1.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [-0.,  0., -0., -0., -0.,  1.]])

In [11]:
# seguindo agora multiplicando por X

beta = np.dot(np.linalg.inv(np.dot(g.T,g)),g.T)
beta

array([[-4.32740691e-01,  1.45692721e+01,  1.58403220e+00,
        -8.18181818e+00, -1.15129151e+00, -5.38745387e+00],
       [ 2.40858772e-02,  2.11338477e-03,  7.64844012e-03,
         1.81818182e-02, -3.17343173e-02, -2.02952030e-02],
       [-9.09090909e-02,  9.09090909e-02,  9.09090909e-02,
        -9.09090909e-02, -8.67361738e-15, -2.86978603e-14],
       [ 7.48742033e-01, -1.19892653e+00,  1.84837303e-01,
         2.72727273e-01,  6.64206642e-02, -7.38007380e-02],
       [ 5.83696746e-01, -9.69808789e+00, -1.76450855e+00,
         5.45454545e+00,  1.18081181e+00,  4.24354244e+00],
       [-1.38879571e-01,  2.38510567e-01,  6.03824220e-03,
        -9.09090909e-02,  1.32841328e-01, -1.47601476e-01]])

In [12]:
# agora multiplicando por Y
beta = np.dot(np.dot(np.linalg.inv(np.dot(g.T,g)),g.T),y)


# uma outra forma seria usando o método .dot já existente em matrizes numpy

beta = np.linalg.inv(g.T.dot(g)).dot(g.T).dot(y)
beta
# lembrando que o primeiro valor é o beta0 ou alfa e os demais são os coeficientes b1 até b5 pois são 5 variáveis

array([-9.42163703e+02,  2.12042939e+00, -5.45454545e+00,  2.37437102e+01,
        6.02918484e+02, -6.94397853e-01])

In [13]:
# podemos arredondar o beta
beta = np.round(beta)
beta
# random forest e algumas classes de SVM nao precisa padronizar os dados (ex: média 0 e variancia 1 ou entre 0 e 1)
# para todas as demais vale fazer a padronização

array([-942.,    2.,   -5.,   24.,  603.,   -1.])

In [14]:
def fit(X,y):
    Xb = np.c_[np.ones((X.shape[0],1)),X]
    beta = np.linalg.inv(Xb.T.dot(Xb)).dot(Xb.T).dot(y)
    intercept = beta[0]
    coefficients = beta[1:]
    return intercept, coefficients

alfa, betas = fit(X,y)

In [15]:
alfa

-942.1637034558288

In [16]:
betas

array([  2.12042939,  -5.45454545,  23.74371016, 602.91848373,
        -0.69439785])

In [17]:
np.r_[alfa,betas]

array([-9.42163703e+02,  2.12042939e+00, -5.45454545e+00,  2.37437102e+01,
        6.02918484e+02, -6.94397853e-01])

In [18]:
Xb = np.c_[np.ones((X.shape[0],1)),X]
Xb.dot(np.r_[alfa,betas])
# comparamos esse resultado com os Y iniciais para avaliar o modelo

array([ 10.,  50., 100., 200.,  70.,  20.])

In [19]:
def predict(X):
    Xb = np.c_[np.ones((X.shape[0],1)),X]
    return Xb.dot(np.r_[alfa,betas]) # concatena alfa e betas em uma mesma matriz

In [21]:
Z = np.array([[40,10,0,1.6,4]])
a = predict(Z)
a

array([50.])

In [23]:
b = predict(np.array([[35,45,0,1.78,4]]))
b

array([-42.98591077])